#!/bin/bash
set -e

source $(dirname $0)/version

cd $(dirname $0)/..

PKG="k8s.io/ingress-nginx"

rm -rf bin/*
mkdir -p bin

declare -a arches=("arm64" "amd64")
for arch in "${arches[@]}"
do
   ARCH=$arch USE_DOCKER=false make build
done
