#!/bin/bash
set -e -x

source $(dirname $0)/version
cd $(dirname $0)/..

# If #GIT_TAG is present, then we release and push to registry
if [[ -n "$GIT_TAG" ]] && [[ -z "$LOCAL" ]]; then
    # manifest push happens as part of make release, so login is required inside the dapper container
    echo "$DOCKER_PASS" | docker login -u $DOCKER_USER --password-stdin
    EXIT_CODE=0
    # Sometimes the push fails with a 500 error, but the image is actually pushed
    # So we ignore the error and check the image exists
    TAG=${NGINX_TAG} make -C images/nginx push || true
    ARCH=$(which go >/dev/null 2>&1 && go env GOARCH)
    docker image inspect rancher/nginx:${NGINX_TAG}-${ARCH}
    make release-ingress-controller || true
else
    TAG=${NGINX_TAG} make -C images/nginx build
    make build-ingress-controller
fi
