#!/bin/bash
set -e -x

source $(dirname $0)/version
cd $(dirname $0)/..

# manifest push happens as part of make release, so login is required inside the dapper container
echo "$DOCKER_PASS" | docker login -u $DOCKER_USER --password-stdin

TAG=${NGINX_TAG} make -C images/nginx push

make release
